# rag/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  namespace: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
        - name: rag-api
          image: localhost:5001/rag-api:latest
          ports:
            - containerPort: 8000            
         
          envFrom:
            - configMapRef:
                name: rag-config

          volumeMounts:
            - name: chroma-data
              mountPath: /data/chroma
      volumes:
        - name: chroma-data
          persistentVolumeClaim:
            claimName: chroma-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
  namespace: rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: rag
spec:
  selector:
    app: rag-api
  ports:
    - port: 8000
      targetPort: 8000
